version: "3.9"
services:
  db:
    image: 'postgres:latest'
    container_name: db
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: appdb
    ports: 
      - "5432:5432"
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    networks:
      - my_network
  server:
    image: server
    container_name: server
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/src/app
    depends_on:
      - db
    networks:
      - my_network
    environment:
      DB_CONNECTION_STRING: postgres://postgres:docker@db:5432/appdb  
    command: sh -c "npx knex migrate:latest && npx knex seed:run && npm start"
  frontend:
    image: frontend
    container_name: frontend
    build: ./frontend
    ports:
    - "3000:3000"
    networks:
      - my_network
    volumes:
      - ./frontend:/src/app
    depends_on:
      - server
networks:
  my_network:
    driver: "bridge"
  
